use crate::config::Config;
use std::fs;
use std::io::Result;
use std::path::PathBuf;

fn skhd_config_dir() -> PathBuf {
    crate::config::home_dir().join(".config").join("skhd")
}

pub fn generate_skhdrc(cfg: &Config) -> Result<()> {
    let dir = skhd_config_dir();
    fs::create_dir_all(&dir)?;

    let home = crate::config::home_dir().to_string_lossy().to_string();

    let mut rc = String::with_capacity(8192);
    rc.push_str("# generated by vimwm\n\n");

    if cfg.vim_mode {
        let speed = cfg.vim_cursor_speed;
        let fast_speed = speed * 5;

        let mb = format!("{home}/.config/vimwm/mouseblock");
        rc.push_str(&format!(":: default : kill $(cat /tmp/vimwm-mouseblock.pid 2>/dev/null) 2>/dev/null; osascript -e 'display notification \"INSERT MODE\" with title \"vimwm\"' &\n"));
        rc.push_str(&format!(":: vim : {mb} & osascript -e 'display notification \"VIM MODE\" with title \"vimwm\"' &\n\n"));

        let toggle = translate_key(&cfg.vim_toggle_key, &cfg.mod_key);
        rc.push_str(&format!("default < {toggle} ; vim\n"));
        rc.push_str(&format!("vim < {toggle} ; default\n"));

        rc.push('\n');

        for (key, action) in &cfg.bindings {
            let skhd_key = translate_key(key, &cfg.mod_key);
            let skhd_action = translate_wm_action(action, &cfg.terminal, &home);
            rc.push_str(&format!("default < {skhd_key} : {skhd_action}\n"));
        }

        rc.push('\n');

        for (key, action) in &cfg.vim_bindings {
            let skhd_key = translate_vim_key(key);
            let skhd_action = translate_vim_action(action, speed, fast_speed, &home);

            if action == "exit" {
                rc.push_str(&format!("vim < {skhd_key} ; default\n"));
            } else {
                rc.push_str(&format!("vim < {skhd_key} : {skhd_action}\n"));
            }
        }

        rc.push('\n');
        for (key, action) in &cfg.bindings {
            let skhd_key = translate_key(key, &cfg.mod_key);
            let skhd_action = translate_wm_action(action, &cfg.terminal, &home);
            rc.push_str(&format!("vim < {skhd_key} : {skhd_action}\n"));
        }
    } else {
        for (key, action) in &cfg.bindings {
            let skhd_key = translate_key(key, &cfg.mod_key);
            let skhd_action = translate_wm_action(action, &cfg.terminal, &home);
            rc.push_str(&format!("{skhd_key} : {skhd_action}\n"));
        }
    }

    fs::write(dir.join("skhdrc"), rc)
}

fn translate_key(key: &str, mod_key: &str) -> String {
    let parts: Vec<&str> = key.split('+').collect();
    let mut modifiers = Vec::new();
    let mut trigger = String::new();

    for part in parts {
        match part {
            "mod" => modifiers.push(mod_key.to_string()),
            "shift" => modifiers.push("shift".into()),
            "ctrl" => modifiers.push("ctrl".into()),
            "cmd" => modifiers.push("cmd".into()),
            k => trigger = translate_trigger(k),
        }
    }

    if modifiers.is_empty() {
        trigger
    } else {
        format!("{} - {}", modifiers.join(" + "), trigger)
    }
}

fn translate_vim_key(key: &str) -> String {
    let parts: Vec<&str> = key.split('+').collect();
    let mut modifiers: Vec<String> = Vec::new();
    let mut trigger = String::new();

    for part in parts {
        match part {
            "shift" => modifiers.push("shift".into()),
            "ctrl" => modifiers.push("ctrl".into()),
            "cmd" => modifiers.push("cmd".into()),
            k => trigger = translate_trigger(k),
        }
    }

    if modifiers.is_empty() {
        trigger
    } else {
        format!("{} - {}", modifiers.join(" + "), trigger)
    }
}

fn translate_trigger(key: &str) -> String {
    match key {
        "enter" | "return" => "return".into(),
        "equal" => "0x18".into(),
        "minus" => "0x1B".into(),
        "tab" => "0x30".into(),
        "space" => "space".into(),
        "escape" => "escape".into(),
        "slash" => "0x2C".into(),
        k => k.into(),
    }
}

fn translate_vim_action(action: &str, speed: u32, fast_speed: u32, home: &str) -> String {
    let parts: Vec<&str> = action.splitn(2, ' ').collect();
    let cmd = parts[0];
    let arg = parts.get(1).unwrap_or(&"");
    let bin = format!("{home}/.config/vimwm");

    match cmd {
        "cursor" => {
            let (dx, dy) = match *arg {
                "left"       => (-(speed as i32), 0),
                "right"      => (speed as i32, 0),
                "up"         => (0, -(speed as i32)),
                "down"       => (0, speed as i32),
                "left-fast"  => (-(fast_speed as i32), 0),
                "right-fast" => (fast_speed as i32, 0),
                "up-fast"    => (0, -(fast_speed as i32)),
                "down-fast"  => (0, fast_speed as i32),
                _ => (0, 0),
            };
            format!("{bin}/cursor {dx} {dy}")
        }
        "click" => {
            match *arg {
                "left" => format!("{bin}/click left"),
                "right" => format!("{bin}/click right"),
                "double" => format!("{bin}/click double"),
                _ => format!("{bin}/click left"),
            }
        }
        "scroll" => {
            match *arg {
                "up"        => format!("{bin}/scroll 3"),
                "up-fast"   => format!("{bin}/scroll 10"),
                "down"      => format!("{bin}/scroll -3"),
                "down-fast" => format!("{bin}/scroll -10"),
                _ => format!("echo 'unknown scroll: {arg}'"),
            }
        }
        "key" => {
            translate_key_action(arg, home)
        }
        "exit" => String::new(),
        _ => format!("echo 'unknown vim action: {action}'"),
    }
}

fn translate_key_action(combo: &str, home: &str) -> String {
    let bin = format!("{home}/.config/vimwm/key");
    let parts: Vec<&str> = combo.split_whitespace().collect();

    let mut cmds: Vec<String> = Vec::new();
    let mut i = 0;
    while i < parts.len() {
        let part = if parts[i] == "key" && i + 1 < parts.len() {
            i += 1;
            parts[i]
        } else {
            parts[i]
        };
        i += 1;

        let segs: Vec<&str> = part.split('-').collect();
        let key_name = segs.last().unwrap_or(&"");
        let mods: Vec<&str> = segs[..segs.len().saturating_sub(1)].to_vec();

        let key_code = match *key_name {
            "a" => "0", "s" => "1", "d" => "2", "f" => "3",
            "h" => "4", "g" => "5", "z" => "6", "x" => "7",
            "c" => "8", "v" => "9", "b" => "11", "q" => "12",
            "w" => "13", "e" => "14", "r" => "15", "y" => "16",
            "t" => "17", "o" => "31", "n" => "45",
            "left" => "123", "right" => "124", "down" => "125", "up" => "126",
            "delete" => "51", "backspace" => "51", "return" => "36",
            "tab" | "0x30" => "48",
            "pageup" => "116", "pagedown" => "121",
            "home" => "115", "end" => "119",
            other => other,
        };

        let mut mod_args: Vec<&str> = Vec::new();
        for m in &mods {
            match *m {
                "cmd" => mod_args.push("cmd"),
                "shift" => mod_args.push("shift"),
                "alt" => mod_args.push("alt"),
                "ctrl" => mod_args.push("ctrl"),
                _ => {}
            }
        }

        if mod_args.is_empty() {
            cmds.push(format!("{bin} {key_code}"));
        } else {
            cmds.push(format!("{bin} {key_code} {}", mod_args.join(" ")));
        }
    }

    cmds.join(" && ")
}

fn translate_wm_action(action: &str, terminal: &str, home: &str) -> String {
    let parts: Vec<&str> = action.splitn(2, ' ').collect();
    let cmd = parts[0];
    let arg = parts.get(1).unwrap_or(&"");

    match cmd {
        "focus" => format!("yabai -m window --focus {}", translate_direction(arg)),
        "move" => format!("yabai -m window --swap {}", translate_direction(arg)),
        "space" => {
            let key_code = match *arg {
                "1" => "18", "2" => "19", "3" => "20", "4" => "21",
                "5" => "23", "6" => "22", "7" => "26", "8" => "28", "9" => "25",
                _ => "",
            };
            if key_code.is_empty() {
                format!("yabai -m space --focus {arg}")
            } else {
                format!("{home}/.config/vimwm/key {key_code} ctrl")
            }
        }
        "move-to-space" => format!("yabai -m window --space {arg} && yabai -m space --focus {arg}"),
        "terminal" => format!("open -na {terminal}"),
        "close" => "yabai -m window --close".into(),
        "fullscreen" => "yabai -m window --toggle zoom-fullscreen".into(),
        "toggle-float" => "yabai -m window --toggle float --grid 4:4:1:1:2:2".into(),
        "rotate" => "yabai -m space --rotate 270".into(),
        "reload" => "vimwm reload".into(),
        "stop" => "vimwm stop".into(),
        "layout-cycle" => {
            r#"bash -c "cur=\$(yabai -m query --spaces --space | tr ',' '\n' | grep type | cut -d'\"' -f4); case \$cur in bsp) yabai -m space --layout stack;; stack) yabai -m space --layout float;; *) yabai -m space --layout bsp;; esac""#.into()
        }
        "split-vertical" => "yabai -m window --insert south".into(),
        "split-horizontal" => "yabai -m window --insert east".into(),
        "gaps-inc" => "yabai -m space --gap rel:5".into(),
        "gaps-dec" => "yabai -m space --gap rel:-5".into(),
        "padding-inc" => "yabai -m space --padding rel:5:5:5:5".into(),
        "padding-dec" => "yabai -m space --padding rel:-5:-5:-5:-5".into(),
        "focus-recent" => "yabai -m space --focus recent".into(),
        "balance" => "yabai -m space --balance".into(),
        "resize" => {
            match *arg {
                "shrink-width" => "yabai -m window --resize left:-50:0".into(),
                "grow-width" => "yabai -m window --resize right:50:0".into(),
                "shrink-height" => "yabai -m window --resize top:0:-50".into(),
                "grow-height" => "yabai -m window --resize bottom:0:50".into(),
                _ => format!("echo 'unknown resize: {arg}'"),
            }
        }
        _ => format!("echo 'unknown action: {action}'"),
    }
}

fn translate_direction(dir: &str) -> &str {
    match dir {
        "west" | "left" => "west",
        "east" | "right" => "east",
        "north" | "up" => "north",
        "south" | "down" => "south",
        other => other,
    }
}
