use crate::config::Config;
use std::fs;
use std::io::Result;
use std::path::PathBuf;

fn yabai_config_dir() -> PathBuf {
    crate::config::home_dir().join(".config").join("yabai")
}

pub fn generate_yabairc(cfg: &Config) -> Result<()> {
    let dir = yabai_config_dir();
    fs::create_dir_all(&dir)?;

    let mut rc = String::with_capacity(2048);

    rc.push_str("#!/usr/bin/env sh\n");
    rc.push_str("# generated by vimwm\n\n");
    rc.push_str("yabai -m signal --add event=dock_did_restart action=\"sudo yabai --load-sa\"\n");
    rc.push_str("sudo yabai --load-sa\n\n");

    rc.push_str(&format!("yabai -m config layout {}\n", cfg.layout));
    rc.push_str(&format!("yabai -m config split_ratio {}\n", cfg.split_ratio));

    rc.push_str(&format!("yabai -m config top_padding {}\n", cfg.padding));
    rc.push_str(&format!("yabai -m config bottom_padding {}\n", cfg.padding));
    rc.push_str(&format!("yabai -m config left_padding {}\n", cfg.padding));
    rc.push_str(&format!("yabai -m config right_padding {}\n", cfg.padding));
    rc.push_str(&format!("yabai -m config window_gap {}\n", cfg.gap_size));

    rc.push_str(&format!(
        "yabai -m config focus_follows_mouse {}\n",
        if cfg.focus_follows_mouse { "autofocus" } else { "off" }
    ));
    rc.push_str(&format!(
        "yabai -m config mouse_follows_focus {}\n",
        if cfg.mouse_follows_focus { "on" } else { "off" }
    ));

    rc.push_str(&format!("yabai -m config mouse_modifier {}\n", cfg.mod_key));
    rc.push_str("yabai -m config mouse_action1 move\n");
    rc.push_str("yabai -m config mouse_action2 resize\n");
    rc.push_str("yabai -m config mouse_drop_action swap\n");

    rc.push_str(&format!(
        "yabai -m config window_opacity {}\n",
        if cfg.window_opacity { "on" } else { "off" }
    ));

    rc.push_str("yabai -m config auto_balance off\n");
    rc.push_str("yabai -m config window_placement second_child\n");

    if !cfg.external_bar.is_empty() {
        rc.push_str(&format!("yabai -m config external_bar {}\n", cfg.external_bar));
    }

    rc.push('\n');
    let float_apps = [
        "System Preferences",
        "System Settings",
        "Calculator",
        "Karabiner-Elements",
        "Archive Utility",
        "Activity Monitor",
        "Installer",
        "Font Book",
        "ColorSync Utility",
        "Digital Color Meter",
    ];
    for app in float_apps {
        rc.push_str(&format!("yabai -m rule --add app=\"{app}\" manage=off\n"));
    }

    let path = dir.join("yabairc");
    fs::write(&path, rc)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&path, fs::Permissions::from_mode(0o755))?;
    }

    Ok(())
}
