use std::collections::BTreeMap;
use super::parser::Config;

pub fn default_config() -> Config {
    Config {
        mod_key: "alt".into(),
        terminal: "alacritty".into(),
        layout: "bsp".into(),
        gap_size: 8,
        padding: 8,
        focus_follows_mouse: false,
        mouse_follows_focus: false,
        window_opacity: false,
        active_opacity: 1.0,
        inactive_opacity: 0.9,
        border: true,
        border_width: 2,
        active_border_color: "0xff88c0d0".into(),
        inactive_border_color: "0xff3b4252".into(),
        external_bar: String::new(),
        split_ratio: 0.5,
        vim_mode: true,
        vim_toggle_key: "mod+space".into(),
        vim_cursor_speed: 50,
        bindings: default_bindings(),
        vim_bindings: default_vim_bindings(),
    }
}

fn default_bindings() -> BTreeMap<String, String> {
    let pairs = [
        ("mod+h", "focus west"),
        ("mod+j", "focus south"),
        ("mod+k", "focus north"),
        ("mod+l", "focus east"),
        ("mod+shift+h", "move west"),
        ("mod+shift+j", "move south"),
        ("mod+shift+k", "move north"),
        ("mod+shift+l", "move east"),
        ("mod+1", "space 1"),
        ("mod+2", "space 2"),
        ("mod+3", "space 3"),
        ("mod+4", "space 4"),
        ("mod+5", "space 5"),
        ("mod+6", "space 6"),
        ("mod+7", "space 7"),
        ("mod+8", "space 8"),
        ("mod+9", "space 9"),
        ("mod+shift+1", "move-to-space 1"),
        ("mod+shift+2", "move-to-space 2"),
        ("mod+shift+3", "move-to-space 3"),
        ("mod+shift+4", "move-to-space 4"),
        ("mod+shift+5", "move-to-space 5"),
        ("mod+shift+6", "move-to-space 6"),
        ("mod+shift+7", "move-to-space 7"),
        ("mod+shift+8", "move-to-space 8"),
        ("mod+shift+9", "move-to-space 9"),
        ("mod+enter", "terminal"),
        ("mod+shift+q", "close"),
        ("mod+f", "fullscreen"),
        ("mod+shift+space", "toggle-float"),
        ("mod+r", "rotate"),
        ("mod+shift+r", "reload"),
        ("mod+shift+e", "stop"),
        ("mod+e", "layout-cycle"),
        ("mod+v", "split-vertical"),
        ("mod+s", "split-horizontal"),
        ("mod+equal", "gaps-inc"),
        ("mod+minus", "gaps-dec"),
        ("mod+shift+equal", "padding-inc"),
        ("mod+shift+minus", "padding-dec"),
        ("mod+tab", "focus-recent"),
        ("mod+shift+b", "balance"),
    ];

    pairs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect()
}

fn default_vim_bindings() -> BTreeMap<String, String> {
    let pairs = [
        ("h", "key left"),
        ("j", "key down"),
        ("k", "key up"),
        ("l", "key right"),
        ("shift+h", "key shift-left"),
        ("shift+j", "key shift-down"),
        ("shift+k", "key shift-up"),
        ("shift+l", "key shift-right"),
        ("w", "key alt-right"),
        ("b", "key alt-left"),
        ("shift+w", "key shift-alt-right"),
        ("shift+b", "key shift-alt-left"),
        ("0", "key cmd-left"),
        ("4", "key cmd-right"),
        ("g", "key cmd-up"),
        ("shift+g", "key cmd-down"),
        ("u", "key pageup"),
        ("d", "key pagedown"),
        ("ctrl+u", "key pageup"),
        ("ctrl+d", "key pagedown"),
        ("y", "key cmd-c"),
        ("p", "key cmd-v"),
        ("x", "key delete"),
        ("shift+x", "key backspace"),
        ("o", "key cmd-right key return"),
        ("shift+o", "key cmd-left key return key up"),
        ("a", "key right"),
        ("shift+a", "key cmd-right"),
        ("shift+i", "key cmd-left"),
        ("slash", "key cmd-f"),
        ("n", "key cmd-g"),
        ("shift+n", "key cmd-shift-g"),
        ("ctrl+z", "key cmd-z"),
        ("ctrl+r", "key cmd-shift-z"),
        ("tab", "key ctrl-0x30"),
        ("shift+tab", "key ctrl-shift-0x30"),
        ("ctrl+w", "key alt-backspace"),
        ("i", "exit"),
        ("escape", "exit"),
    ];
    pairs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect()
}
